// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemainId      int32                  `protobuf:"varint,1,opt,name=remain_id,json=remainId,proto3" json:"remain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemainRequest) Reset() {
	*x = RemainRequest{}
	mi := &file_api_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemainRequest) ProtoMessage() {}

func (x *RemainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemainRequest.ProtoReflect.Descriptor instead.
func (*RemainRequest) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *RemainRequest) GetRemainId() int32 {
	if x != nil {
		return x.RemainId
	}
	return 0
}

type RemainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemainId      int32                  `protobuf:"varint,1,opt,name=remain_id,json=remainId,proto3" json:"remain_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemainResponse) Reset() {
	*x = RemainResponse{}
	mi := &file_api_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemainResponse) ProtoMessage() {}

func (x *RemainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemainResponse.ProtoReflect.Descriptor instead.
func (*RemainResponse) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *RemainResponse) GetRemainId() int32 {
	if x != nil {
		return x.RemainId
	}
	return 0
}

func (x *RemainResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RemainResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ListRemainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemainsRequest) Reset() {
	*x = ListRemainsRequest{}
	mi := &file_api_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemainsRequest) ProtoMessage() {}

func (x *ListRemainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemainsRequest.ProtoReflect.Descriptor instead.
func (*ListRemainsRequest) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ListRemainsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRemainsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRemainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remains       []*RemainResponse      `protobuf:"bytes,1,rep,name=remains,proto3" json:"remains,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemainsResponse) Reset() {
	*x = ListRemainsResponse{}
	mi := &file_api_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemainsResponse) ProtoMessage() {}

func (x *ListRemainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemainsResponse.ProtoReflect.Descriptor instead.
func (*ListRemainsResponse) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ListRemainsResponse) GetRemains() []*RemainResponse {
	if x != nil {
		return x.Remains
	}
	return nil
}

func (x *ListRemainsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateRemainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRemainRequest) Reset() {
	*x = CreateRemainRequest{}
	mi := &file_api_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRemainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRemainRequest) ProtoMessage() {}

func (x *CreateRemainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRemainRequest.ProtoReflect.Descriptor instead.
func (*CreateRemainRequest) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRemainRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateRemainRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeleteRemainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRemainResponse) Reset() {
	*x = DeleteRemainResponse{}
	mi := &file_api_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRemainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemainResponse) ProtoMessage() {}

func (x *DeleteRemainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemainResponse.ProtoReflect.Descriptor instead.
func (*DeleteRemainResponse) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRemainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRemainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRemainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemainRequest) Reset() {
	*x = UpdateRemainRequest{}
	mi := &file_api_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemainRequest) ProtoMessage() {}

func (x *UpdateRemainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemainRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemainRequest) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRemainRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateRemainRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_api_inventory_proto protoreflect.FileDescriptor

const file_api_inventory_proto_rawDesc = "" +
	"\n" +
	"\x13api/inventory.proto\x12\tinventory\",\n" +
	"\rRemainRequest\x12\x1b\n" +
	"\tremain_id\x18\x01 \x01(\x05R\bremainId\"d\n" +
	"\x0eRemainResponse\x12\x1b\n" +
	"\tremain_id\x18\x01 \x01(\x05R\bremainId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"B\n" +
	"\x12ListRemainsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"k\n" +
	"\x13ListRemainsResponse\x123\n" +
	"\aremains\x18\x01 \x03(\v2\x19.inventory.RemainResponseR\aremains\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"L\n" +
	"\x13CreateRemainRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"J\n" +
	"\x14DeleteRemainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x13UpdateRemainRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number2\x86\x03\n" +
	"\x10InventoryService\x12A\n" +
	"\n" +
	"GetRemains\x12\x18.inventory.RemainRequest\x1a\x19.inventory.RemainResponse\x12O\n" +
	"\x0eGetListRemains\x12\x1d.inventory.ListRemainsRequest\x1a\x1e.inventory.ListRemainsResponse\x12I\n" +
	"\fCreateRemain\x12\x1e.inventory.CreateRemainRequest\x1a\x19.inventory.RemainResponse\x12I\n" +
	"\fDeleteRemain\x12\x18.inventory.RemainRequest\x1a\x1f.inventory.DeleteRemainResponse\x12H\n" +
	"\vGiveToOrder\x12\x1e.inventory.UpdateRemainRequest\x1a\x19.inventory.RemainResponseB\x10Z\x0eapi/;inventoryb\x06proto3"

var (
	file_api_inventory_proto_rawDescOnce sync.Once
	file_api_inventory_proto_rawDescData []byte
)

func file_api_inventory_proto_rawDescGZIP() []byte {
	file_api_inventory_proto_rawDescOnce.Do(func() {
		file_api_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_inventory_proto_rawDesc), len(file_api_inventory_proto_rawDesc)))
	})
	return file_api_inventory_proto_rawDescData
}

var file_api_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_inventory_proto_goTypes = []any{
	(*RemainRequest)(nil),        // 0: inventory.RemainRequest
	(*RemainResponse)(nil),       // 1: inventory.RemainResponse
	(*ListRemainsRequest)(nil),   // 2: inventory.ListRemainsRequest
	(*ListRemainsResponse)(nil),  // 3: inventory.ListRemainsResponse
	(*CreateRemainRequest)(nil),  // 4: inventory.CreateRemainRequest
	(*DeleteRemainResponse)(nil), // 5: inventory.DeleteRemainResponse
	(*UpdateRemainRequest)(nil),  // 6: inventory.UpdateRemainRequest
}
var file_api_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.ListRemainsResponse.remains:type_name -> inventory.RemainResponse
	0, // 1: inventory.InventoryService.GetRemains:input_type -> inventory.RemainRequest
	2, // 2: inventory.InventoryService.GetListRemains:input_type -> inventory.ListRemainsRequest
	4, // 3: inventory.InventoryService.CreateRemain:input_type -> inventory.CreateRemainRequest
	0, // 4: inventory.InventoryService.DeleteRemain:input_type -> inventory.RemainRequest
	6, // 5: inventory.InventoryService.GiveToOrder:input_type -> inventory.UpdateRemainRequest
	1, // 6: inventory.InventoryService.GetRemains:output_type -> inventory.RemainResponse
	3, // 7: inventory.InventoryService.GetListRemains:output_type -> inventory.ListRemainsResponse
	1, // 8: inventory.InventoryService.CreateRemain:output_type -> inventory.RemainResponse
	5, // 9: inventory.InventoryService.DeleteRemain:output_type -> inventory.DeleteRemainResponse
	1, // 10: inventory.InventoryService.GiveToOrder:output_type -> inventory.RemainResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_inventory_proto_init() }
func file_api_inventory_proto_init() {
	if File_api_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_inventory_proto_rawDesc), len(file_api_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_inventory_proto_goTypes,
		DependencyIndexes: file_api_inventory_proto_depIdxs,
		MessageInfos:      file_api_inventory_proto_msgTypes,
	}.Build()
	File_api_inventory_proto = out.File
	file_api_inventory_proto_goTypes = nil
	file_api_inventory_proto_depIdxs = nil
}
